name: YahooRequests Run
on:
  push:
    branches:
      - main
jobs:
  YahooRequests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Python, install dependencies
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Check Python version
        run: python -V
            
      - name: Install dependencies
        run: pip install requests tabulate datetime
      # Step 4: Define environment variables
      - name: Set environment variables
        run: echo "OER_KEY=${{ secrets.OER_KEY }}" >> $GITHUB_ENV; echo "NEWS_KEY=${{ secrets.NEWS_KEY }}" >> $GITHUB_ENV
      # Step 6: Run the code
      - name: Run YahooRequests
        run: python YahooRequests/yahoorequests.py
