name: YahooRequests Test & Run
on:
  push:
    branches:
      - main
jobs:
  YahooRequests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Python, install dependencies
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Install pytest
        run: pip install pytest
      # Step 4: Define environment variables
      - name: Set environment variables
        run: echo "OER=${{ secrets.OER }}" >> $GITHUB_ENV
      # Step 5: Test the program
      - name: Run tests
        run: pytest test_project.py
      # Step 6: Run the code
      - name: Run my script
        run: python YahooRequests/yahoorequests.py
