name: YahooRequests Test
on:
  push:
    branches:
      - main
jobs:
  YahooRequests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Set up Python, install dependencies
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Install tabulate
        run: pip install tabulate
      - name: Install pytest
        run: pip install pytest
      # Step 4: Define environment variables
      - name: Set environment variables
        run: echo "OER_KEY=${{ secrets.OER_KEY }}" >> $GITHUB_ENV; echo "NEWS_KEY=${{ secrets.NEWS_KEY }}" >> $GITHUB_ENV
      # Step 5: Test the program
      - name: Run tests
        run: pytest test_yahoorequests.py
